### ISSUE TITLE
"openid" scope should be selected by default

### ISSUE THREAD

**Issue by alvarolopez** [indigo-iam/iam#13]
According to OpenID's specification (https://openid.net/specs/openid-connect-basic-1_0.html#Scopes) the "openid" scope is mandatory. However, a user can uncheck it (actually, it is not checked by default), therefore a request using an scope like "openid profile" will fail with the following error:

    RESP BODY: {"error":"invalid_scope","error_description":"Invalid scope; requested:[openid, profile]","scope":"address phone email profile"}

I think that "openid" should be uncheckable, or at least it should be checked by default.

**Comment by andreaceccanti** [comment]
Hi Alvaro,

> According to OpenID's specification (https://openid.net/specs/openid-connect-basic-1_0.html#Scopes) the "openid" scope is mandatory. 

To start an OpenID-Connect flow for sure. The MitreID connect implementation we extend also accomodates pure OAuth2 clients, for which the openid scopes are not required.

We can for sure change the UI so that the openid scope is by default checked when registering a new client.

Thanks.

**Comment by alvarolopez** [comment]
@andreaceccanti many thanks!

**Comment by andreaceccanti** [comment]
I believe this is not an issue currently, so I am closing it.
