### ISSUE TITLE
Formatting of the AUP Field

### ISSUE THREAD

**Issue by norealroots** [indigo-iam/iam#285]
I have previously submitted a pull request (merged in #284) to fix the column width of the AUP, however this is an area which could still be improved.

The AUP is presented in two separate places: to a new user when registering and to an existing user at sign in. The issue here is that the two fields offer very little to no formatting options, making it difficult to present an AUP which is easy to read - there is no ability to have bullet points, numbered sections, or line breaks. 

I feel the best solution to this would be to have both locations render the text using markdown, enabling IAM administrators to format their AUP as desired. As any user should be required to view the AUP before accessing the service, I feel this solution is preferable to linking to an externally hosted AUP.

###### Existing User View:
![existingUser](https://user-images.githubusercontent.com/22589560/61618710-4fae2d00-ac65-11e9-9ed9-03161f1131a5.png)

###### New User View:
![newUser](https://user-images.githubusercontent.com/22589560/61618717-550b7780-ac65-11e9-971d-984f436eaa07.png)

**Comment by hannahshort** [comment]
I support this request

**Comment by andreaceccanti** [comment]
I think having the AUP text embedded in the IAM db was a bad design decision (shame on me). 

In a future release, we are going to change the db structure so that a URL is kept in the db instead of the AUP text. 

This will let the deployer have more control on how the AUP is presented, its format (it could be a pdf) etc... and will be simpler to handle at the IAM level.

**Comment by andreaceccanti** [comment]
Closing this in favour of #287 .
