### ISSUE TITLE
Cannot create new user with email address ending in `.es`

### ISSUE THREAD

**Issue by orviz** [indigo-iam/iam#302]
When creating a new user, the [DEEP IAM instance](https://iam.deep-hybrid-datacloud.eu) surprinsingly does not accept domains ending in `.es` within the email address. Whatever other combination seems to work, see attached images.

IAM version: IAM 1.4.0 (e0a8e7f)

![image](https://user-images.githubusercontent.com/1225231/66562749-90c72680-eb5c-11e9-9a9f-f97ddf9c403e.png)

![image](https://user-images.githubusercontent.com/1225231/66563073-46927500-eb5d-11e9-8f7b-c2d897070e47.png)

**Comment by andreaceccanti** [comment]
Hi Pablo,
thanks for reporting the issue.

I think this is now fixed in the IAM development branch:

<img width="489" alt="Screenshot 2019-10-10 15 20 49" src="https://user-images.githubusercontent.com/1152853/66572879-0b4e7100-eb72-11e9-9661-551b08876a94.png">

We can schedule an upgrade for the DEEP IAM instance, if this is a blocking issue for you.
HTH,
A.

**Comment by orviz** [comment]
no problem, I used a `.com`, so no real rush for me
