### ISSUE TITLE
OAuth2 as external identity provider in IAM

### ISSUE THREAD

**Issue by maiev-dev** [indigo-iam/iam#398]
Hello, 

We are considering the possibility of using IAM at JINR and we need to link it to our institutional SSO as an external identity provider, which is based on OAuth2. As I get the IAM only supports OIDC, which also is based on OAuth2, but differs from the JINR SSO flow. Our flow looks like this:

1) Request authorization of an application:
http://login.jinr.ru/cgi-bin/authorize?client_id=*app id*[&backurl=*back url*]
2) On success we get redirected back to the app site with the code:
http://some_app.jinr.ru/token?code=*confirmation code*
3) The code is then exchanged for the access token with the POST:
http://login.jinr.ru/cgi-bin/token with params code=our_code&client_id=app_id&pass=app_pass
4) The SSO then responds with access token that looks like this:
{ "access_token": "some_value", "expires_in": time } 
5) And this token is then used to request the user information:
http://login.jinr.ru/cgi-bin/infojson?access_token=token

So, the question is: is there a way to somehow integrate the IAM in its current implementation with that kind of flow?

**Comment by andreaceccanti** [comment]
Hi,

> So, the question is: is there a way to somehow integrate the IAM in its current implementation with that kind of flow?

From the top of my head I'd say no, but it should be investigated.
Currently IAM does support OIDC and SAML external authentication.  I fear development would be required In order to support a custom oauth authentication flow like the one you describe. 

My suggestion would be to migrate your SSO to use a standard protocol, either OIDC (if possible) or SAML. That would have other benefits beside the integration with IAM.
