### ISSUE TITLE
Performance collapse with lots of access tokens with "clear access tokens on refresh" enabled

### ISSUE THREAD

**Issue by enricovianello** [indigo-iam/iam#580]
With thousands and thousands of access tokens, we observed slowness for some clients when doing a refresh flow in case all the existent access tokens are cleared ("clear access tokens on refresh" client setting is enabled).

The MitreID logic in fact is that:
- a select is done (`select a from OAuth2AccessTokenEntity a where a.refreshToken = <RT>`)
- a one-by-one deletion of tokens

**Comment by vokac** [comment]
It seems to me that main problem comes from really poor DB table index choices done by MitreID developers (discussed also in the https://github.com/indigo-iam/iam/issues/579). I think that most expensive is not access token deletion one-by-one, but query that lists these tokens, because there is no index on `refresh_token_id` in `access_token`.

Refreshing tokens with our instance takes between 5-20s and that leads to problems with clients like `oidc-agent` which reach internal timeout before it gets response from IAM.
![atlas_iam_refresh_token_performance](https://user-images.githubusercontent.com/5621854/227722690-38e268ac-dcbc-42ac-9578-b936594589cc.png)
(faster responses around noon on March 23 was caused by removing "Clear access tokens on refresh")

Would it make sense to just add index mentioned above to our production IAM instance?

**Comment by federicaagostini** [comment]
Solved in #632
