### ISSUE TITLE
IAM admins should be able to suspend clients

### ISSUE THREAD

**Issue by maarten-litmaath** [indigo-iam/iam#705]
IAM admins should be able to suspend clients:

- that are suspicious in some way, or
- that have unknown owners (cf. #595, #652), or
- that are misbehaving (cf. #386), or
- for some other reason.

If nobody complains about a particular client being suspended, it probably can be manually deleted as part of a cleanup operation.

**Comment by garaimanoj** [comment]
If a client is suspended which operations, done by the client, do we need to stop?
For example, 
- New action token request
- Invalid refresh token issued by the client

Is there anything else we need to take care of?

**Comment by federicaagostini** [comment]
Our conclusion after last IAM community meeting was that:
- in case of suspended client, new access tokens cannot be issued anymore
- RT may be still valid, but one cannot use the RT flow to get tokens.

If there is a security leak, we think the client should be deleted (with the consequence of all AT/RT being deleted as well).
Likely, the reason for disabling a client could be a temporary misbehavior, and we can leave the RT valid for instance to not force a user to set up oidc-agent again once the client will be re-enabled -- also, we do not see the difference between removing and disabling a client, otherwise.

What do you @giacomini and @maarten-litmaath think about it?

**Comment by giacomini** [comment]
Should we also record the date of the suspension and show it in the dashboard and/or make it available in a search?

**Comment by maarten-litmaath** [comment]
It would be good to have the date shown indeed.  What about who did it?

**Comment by federicaagostini** [comment]
PR #747

**Comment by enricovianello** [comment]
This is an example of the new Disable Client button inside Client Edit page:

![Image](https://github.com/indigo-iam/iam/assets/1914039/0fe12c9e-e3d5-449e-bec8-9917c192f6c6)

The confirmation dialog:

![Image](https://github.com/indigo-iam/iam/assets/1914039/be6e6406-b5b3-4422-b05f-bdcd127fbc79)

How the client is shown into client list:

![Image](https://github.com/indigo-iam/iam/assets/1914039/75b0fca9-8437-4365-addb-d5ee4696cd75)
