### ISSUE TITLE
User registration needs option for nickname to be added

### ISSUE THREAD

**Issue by maarten-litmaath** [indigo-iam/iam#770]
ATLAS and LHCb make use of the nickname attribute and set it to the primary CERN account name of the user. There should be an option for the IAM registration procedure to set it automatically.

**Comment by chaen** [comment]
Indeed ! It would also be nice if this could be made read-only for the user, as DIRAC uses it as a primary identifier for the user :-)

**Comment by maarten-litmaath** [comment]
Not just nice: it **must** be read-only, like various other fields...

**Comment by vokac** [comment]
Actually, attributes are already sufficiently "read-only", because they can be changed only by IAM administrator (who should understand potential mess that could be caused by updating `nickname` attribute).

It would be really useful if IAM could automatically create `nickname` attribute during registration, because together with top level VO group (https://github.com/indigo-iam/iam/issues/758) this must be now manually added to each new account to be able to get correct X.509 VOMS extension.

**Comment by maarten-litmaath** [comment]
This issue needs to be added to the [VOMS-Admin EOL tasks](https://github.com/orgs/indigo-iam/projects/8) and be given high priority.

**Comment by rmiccoli** [comment]
Hi, would you prefer to make it configurable? Or to be applied all the time?

**Comment by maarten-litmaath** [comment]
Ciao Roberta,
it needs to be configurable per VO.  Did you have more configurability in mind?
