### ISSUE TITLE
Cannot sign in with STFC shibboleth

### ISSUE THREAD

**Issue by chrishmorris** [indigo-iam/iam#91]
I cannot sign in on https://iam-test.indigo-datacloud.eu/login. 

I tried both STFC Shibboleth servers. I tried my id "cm65" and also "clrc\cm65".

**Comment by andreaceccanti** [comment]
Do you work for INDIGO Datacloud? In which WP? Are you registered in iam-test?
I don't see any chris morris user.

**Comment by andreaceccanti** [comment]
Are you having problems with registration?

**Comment by andreaceccanti** [comment]
It seems to me that STFC shib servers are misconfigured.

**Comment by chrishmorris** [comment]
HI,

No, I am not in INDIGO. Marco Verlato told me of this new service. I am in the West-Life collaboration.

I have registered Indigo account with username chrishmorris and email address chris.morris@stfc.ac.uk<mailto:chris.morris@stfc.ac.uk>.

I tried to login to iam-test. I clicked “SAML” and searched for STFC. There are two shibboleth servers and I chose one arbitrarily. Now I have a popup saying:
   https://shibboleth02.stfc.ac.uk is requesting your username and password. The site says: “Please use your STFC federal userid and password to authenticate”
If I add an invalid password, then the form clears itself. If I enter my correct password, I return to the iam-test login page with a message:
    “Error validating SAML message”.

Is there something I should do to associate my existing Indigo account with my institutional id? If so, then the defect is a usability one, that the message “Error validating SAML message” is uninformative.

Please note some other usability issues:
- “Sign in with SAML” should read “Choose an existing userid to sign in with”, and should have a tooltip that explains it further “use your university or other identity provider”
- page https://iam-test.indigo-datacloud.eu/saml/discovery?entityID=https%3A%2F%2Fiam-test.indigo-datacloud.eu&returnIDParam=idp should be headed “Choose your institution or other Identity Provider” not “Sign in with your IdP “
- The list of IdPs should be prepopulated. It took a moment to discover that I have to click in the input field.
- The provision of two idps for STFC is unhelpful, I have no way of knowing which will work for me

Regards,
Chris

**Comment by andreaceccanti** [comment]
Chris,
thanks for your feedback on usability, but I think your problem is that stfc shib IdPs are misconfigured. 

Properly configured IdPs usually have a nice welcome page where you can enter your credentials. Do these IdPs work for you for other applications?

There are two IdPs for STFC because the EduGAIN metadata gives us two IdPs for STFC. This doesn't happen for properly configured IdPs (like the INFN, or KIT one).

So I suggest you login with your google credentials, if you have those, or just apply for new IAM credentials. You will have the possiblity to link your IAM account later on when STFC IdPS work as expected.

**Comment by marcoverl** [comment]
Hi Andrea, 
i hope is not a problem if i asked West-Life users to use IAM to make some tests with the OneData provider we set up at INFN-Padova, via the OneZone of INFN-CNAF.

About IdPs, consider that West-Life users adopt ARIA (https://www.structuralbiology.eu/update/register) as IdP, that you probably know because it is also involved in the process to join EGI Check-in service, so having ARIA among IAM accepted IdPs would simplify things.

Cheers,
Marco

**Comment by andreaceccanti** [comment]
Hi @marcoverl ,

> About IdPs, consider that West-Life users adopt ARIA 

Currently IAM test integrates IdPs in the eduGAIN interfederation. It seems to me that ARIA is not registered in eduGAIN. 

We can change the IAM configuration to add the ARIA IdP to the list, but to make things work the iam-test should also be accepted as an SP by ARIA, so this is not only on our side, and can take time. 

So for simple OneDATA tests I suggest you use Google or IAM credentials, which have less friction.

Cheers,
A.

**Comment by chrishmorris** [comment]
HI Andrea,

Thank you for your support. I don’t need to log in right now. My intention was to help with testing, not to use the service.

As Marco has said, my real concern is to get ARIA accepted as an IdP.

Meanwhile, I am trying to raise this issue with the right person in STFC. Maybe it is connected with the fact that my STFC id is not accepted by eduGAIN.

Regards,
Chris

**Comment by chrishmorris** [comment]
Hi Andrea,

This is to introduce Callum Smith, who manages the ARIA IdP. Please tell him how to accept iam-test as an SP.

Regards,
Chris

**Comment by andreaceccanti** [comment]
Closing this
